### ISSUE TITLE
Bootstrapping fails to load 

### ISSUE THREAD

**Issue by Traap** [liubang/nvimrc#30]
@liubang  -

Your repository was recommend to me.   I tried to add it to https://github.com/traap/nvims.

My goal was to experiment with and possibly do a YouTube video covering your work.

You can easily repeat my experiment by:

1, installing https://github.com/traap/nvims
2. modify .config/nvims/neovim_distros
3. run nvims and select your repo

It should bootstrap itself.

**Comment by liubang** [comment]
https://github.com/liubang/nvimrc/commit/d7024e9d049cf75dfe0876494da1bb6d4bae2bbb fixed

**Comment by Traap** [comment]
Confirmed.  Thank you.  I will include you nvim setup in an upcoming YouTube video.  I'll let you know when I post so you can get a good laugh.  :)
